### PR TITLE
CDC library - add a "batch sequence" consumer mode, with resuming granularity

### PR DESCRIPTION
**Pull request by elcallio**
Split from #30. Requires #38. 
Adds a consumer abstraction layer, and introduces the ability to subscribe to complete batch sequences - i.e. CDC events. 
See lengthy rationale in #30 for why this is good, and resumability etc. 

PR actually starts at "Add new, common, interface "Change""

### CODE REVIEW

**Comment by elcallio** [comment]
@avelanarius @haaawk - enjoy

**Comment by elcallio** [comment]
ping. Updated printer example + readme.

**Comment by hartmut-co-uk** [comment]
Hi, has this ever been reviewed/planned to be merged?

**Comment by elcallio** [comment]
Yes. But some deliberation determined that there are cases where it does not work so well, so scrapped. Should have closed the PR.

**Pull request closed without merging**
